### ISSUE TITLE
Desktop Home Page Sections: Testimonials, Concierge Services & Blog

### ISSUE THREAD

**Issue by mmmagency** [the-mmm-agency/muskoka-district-rentals#89]
Reduce size by 25% for desktop version so more like mockup aspect ratio:
<img width="1145" alt="Screen Shot 2019-08-02 at 10 19 11 AM" src="https://user-images.githubusercontent.com/50122265/62377720-506e7b00-b511-11e9-896c-5f2f6f382d75.png">
<img width="1145" alt="Screen Shot 2019-08-02 at 10 19 22 AM" src="https://user-images.githubusercontent.com/50122265/62377727-53696b80-b511-11e9-9f24-77c18214c2df.png">
<img width="1145" alt="Screen Shot 2019-08-02 at 10 19 38 AM" src="https://user-images.githubusercontent.com/50122265/62377734-56645c00-b511-11e9-8af2-f44b012d045c.png">

**Comment by Brettm12345** [comment]
This is really difficult with horizontally scrollable elements
