### ISSUE TITLE
Mobile: Add permanent scroll bars

### ISSUE THREAD

**Issue by mmmagency** [the-mmm-agency/muskoka-district-rentals#93]
Add permanent scroll bars to Our Rentals, Testimonials & Blog sections:

![IMG_4474](https://user-images.githubusercontent.com/50122265/62378507-f1aa0100-b512-11e9-97a2-432b1f048199.PNG)
![IMG_4472](https://user-images.githubusercontent.com/50122265/62378496-ece54d00-b512-11e9-9a23-d836c353b375.PNG)
![IMG_4473](https://user-images.githubusercontent.com/50122265/62378501-ef47a700-b512-11e9-8754-a143bea30e11.PNG)

**Comment by Brettm12345** [comment]
That's pretty hard to do for all browsers. I can do it for chrome and safari

**Comment by mmmagency** [comment]
> That's pretty hard to do for all browsers. I can do it for chrome and safari

Ok the reason I ask is because right now, users won't intuitively know that they can scroll to the left in these sections: maybe if you reduce size of section - it can be more apparent to users they can do so cuz they will see half of another section and try to move the screen to get there. right now, most of the sections you can fully see one item on the viewport - it makes it seem like its static part of the page that you can only scroll down on - not left or right.
